# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/EV2/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src/ev2c"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/EV2.EV2LanguageServer.vscode-extension/"
    schedule:
      interval: "daily"
